// типы экшенов
export const LOAD_LIST = 'LOAD_LIST';
export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS';
export const LOAD_LIST_FAILED = 'LOAD_LIST_FAILED';
export const LOAD_DESCRIPTION = 'LOAD_DESCRIPTION';
export const LOAD_DESCRIPTION_SUCCESS = 'LOAD_DESCRIPTION_SUCCESS';
export const LOAD_DESCRIPTION_FAILED = 'LOAD_DESCRIPTION_FAILED';
export const CANCEL = 'CANCEL';
export const UPLOAD_SERVICE = 'UPLOAD_SERVICE';
export const UPLOAD_SERVICE_SUCCESS = 'UPLOAD_SERVICE_SUCCESS';
export const UPLOAD_SERVICE_FAILED = 'UPLOAD_SERVICE_FAILED';